### ISSUE TITLE
ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by baikaresandip** [drawmoon/mhtdoc-to-html#1]
Hi,
I am using this package for converting document to HTML but I am getting error

```
ReferenceError: SharedArrayBuffer is not defined
./node_modules/webidl-conversions/lib/index.js
C:/wamp64/www/demo/zesty/word-conversion/node_modules/webidl-conversions/lib/index.js:347
  344 | 
  345 | const abByteLengthGetter =
  346 |     Object.getOwnPropertyDescriptor(ArrayBuffer.prototype, "byteLength").get;
> 347 | const sabByteLengthGetter =
  348 |     Object.getOwnPropertyDescriptor(SharedArrayBuffer.prototype, "byteLength").get;
  349 | 
  350 | function isNonSharedArrayBuffer(V) {

```

Could you please let me know why I am getting this error?

**Comment by drawmoon** [comment]
First of all, thank you very much for submitting issues:)

I don't know how you use it, Can you provide a small piece of code? The error message it seems to come from `jsdom`, I found `issues` that is very close to your question:

- [https://github.com/jsdom/webidl-conversions/issues/31](https://github.com/jsdom/webidl-conversions/issues/31)

**Comment by yeernet** [comment]
`const converter = new MhtDocToHtml(buffer);
                  ^

TypeError: MhtDocToHtml is not a constructor
`

**Comment by drawmoon** [comment]
I have upgraded the dependency, feel free to open it if you encounter problems
